In [242]:
import numpy as np
import pandas as pd
import zipfile

In [243]:
movies_df=pd.read_csv('movie_df.csv')

In [244]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [245]:
def stem(x):
    List=[]
    x=x.split()
    for i in x:
        List.append(ps.stem(str(i)))
    return " ".join(List)

In [246]:
movies_df['tags']=movies_df['tags'].apply(lambda x:stem(x))

In [247]:
movies_df.head()

Unnamed: 0      id                                     title  \
0           0   19995                                    Avatar   
1           1     285  Pirates of the Caribbean: At World's End   
2           2  206647                                   Spectre   
3           3   49026                     The Dark Knight Rises   
4           4   49529                               John Carter   

                                                tags  
0  action adventur fantasi sciencefict culturecla...  
1  adventur fantasi action ocean drugabu exoticis...  
2  action adventur crime spi basedonnovel secreta...  
3  action crime drama thriller dccomic crimefight...  
4  action adventur sciencefict basedonnovel mar m...

In [248]:
movies_df.to_csv('movie_df.csv')

In [249]:
df=pd.read_csv('movie_df.csv')
df.head()

Unnamed: 0.1  Unnamed: 0      id                                     title  \
0             0           0   19995                                    Avatar   
1             1           1     285  Pirates of the Caribbean: At World's End   
2             2           2  206647                                   Spectre   
3             3           3   49026                     The Dark Knight Rises   
4             4           4   49529                               John Carter   

                                                tags  
0  action adventur fantasi sciencefict culturecla...  
1  adventur fantasi action ocean drugabu exoticis...  
2  action adventur crime spi basedonnovel secreta...  
3  action crime drama thriller dccomic crimefight...  
4  action adventur sciencefict basedonnovel mar m...

In [250]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [251]:
vectors=cv.fit_transform(movies_df['tags']).toarray()

In [252]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [253]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [254]:
from sklearn.metrics.pairwise import cosine_similarity
cos=cosine_similarity(vectors)

In [255]:
cos[0]

array([1.        , 0.2274141 , 0.21053227, ..., 0.22330319, 0.15075567,
       0.11955702])

In [256]:
def sample_30():
    arr=np.array(movies_df.sample(30))
    sample=[row[0] for row in arr]
    return sample
sample_30()

[969,
 3757,
 2394,
 4577,
 3642,
 159,
 135,
 3151,
 3335,
 2992,
 4339,
 1208,
 4277,
 648,
 3154,
 530,
 3884,
 3473,
 843,
 3120,
 3966,
 1314,
 2835,
 1143,
 3800,
 2430,
 936,
 3264,
 2642,
 3553]

In [257]:
def recommand_top_6(movie):
    movie_index = movies_df[movies_df['title'] == movie].index[0]
    distances = cos[movie_index]
    # Get indices of movies sorted by similarity (highest first)
    top_indices = np.argsort(distances)[::-1][1:7]  # Exclude the movie itself
    return top_indices

In [258]:
def recommand_top_7_to_12(movie):
    movie_index = movies_df[movies_df['title'] == movie].index[0]
    distances = cos[movie_index]
    # Get indices of movies sorted by similarity (highest first)
    top_indices = np.argsort(distances)[::-1][7:13]  # Exclude the movie itself
    return top_indices

In [259]:
recommand_top_6('Avatar')

array([1086, 1213,  507, 3604, 2403,  342], dtype=int64)

In [260]:
import pickle
# open a file in binary write mode and dump the object into it
with open('recommand_top_6.pkl', 'wb') as f:
	pickle.dump(recommand_top_6, f)
with open('recommand_top_7_to_12.pkl','wb') as f:
    pickle.dump(recommand_top_7_to_12,f)

In [261]:
with open('sample_30.pkl', 'wb') as f:
	pickle.dump(sample_30, f)

In [262]:
with open('recommand_top_6.pkl','rb') as f:
    rec=pickle.load(f)

In [263]:
with open('sample_30.pkl','rb') as f:
    super_30=pickle.load(f)

In [264]:
super_30()

[30,
 3251,
 3749,
 4592,
 1334,
 4577,
 4470,
 2359,
 3206,
 1603,
 1121,
 4700,
 4216,
 3452,
 340,
 811,
 1331,
 4117,
 3252,
 4088,
 1546,
 4238,
 1717,
 2007,
 3329,
 3522,
 1913,
 180,
 1254,
 4506]

In [265]:
rec('Avatar')

array([1086, 1213,  507, 3604, 2403,  342], dtype=int64)

In [266]:
with open('recommand_top_7_to_12.pkl','rb') as f:
    rec=pickle.load(f)

In [267]:
rec('Avatar')

array([ 300,  582,  539, 3899,  461, 2967], dtype=int64)

In [268]:
def movie_name(List):
    for i in List:
        print(movies_df.iloc[i]['title'])
movie_name(list(recommand_top_6('Avatar')))


Aliens in the Attic
Aliens vs Predator: Requiem
Independence Day
Apollo 18
Aliens
Men in Black
